parser: 'babel-eslint'

extends: 'airbnb/base'

env:
  node: true
  es6: true
  mocha: true

rules:
  semi: [2, 'never']
  arrow-parens: [1, 'as-needed']
  jsx-quotes: [2, 'prefer-single']
  id-length: 0
  no-console: 0
  no-multiple-empty-lines: [2, { max: 5 }]
  no-unused-expressions: 0
  no-param-reassign: [2, { props: false }]

ecmaFeatures:
  module: true
